#!/bin/bash
echo -e "Attention! Important message from your servermaster!"
echo ""
echo -e "	-----------------------------Message----------------------------------"
echo -e "	Here's some handy information about our server:"
echo ""
echo -e "	Architecture: 	"
echo -e "	Physical CPU's: "
echo -e "	vCPU's: 	"
echo -e "	Memory usage: 	" 
echo -e "	Disk usage: 	"
echo -e "	CPU load: 	"
echo -e "	Last boot: 	"
echo -e "	LVM: 		"
echo -e "	Network:	IPv4 "`hostname -I`" MAC "
